### ISSUE TITLE
Game Ping Pong em Java

### ISSUE THREAD

**Issue by jailsonh3** [Jailsonk8/Ping_Pong#1]
# Screenshots of Game
![WhatsApp Image 2019-10-18 at 00 20 07](https://user-images.githubusercontent.com/20127664/67064032-4129c180-f13f-11e9-8560-818fa4efb64e.jpeg)
![WhatsApp Image 2019-10-18 at 00 19 34](https://user-images.githubusercontent.com/20127664/67064033-4129c180-f13f-11e9-9e3f-e2f2b1e7ea67.jpeg)
![WhatsApp Image 2019-10-18 at 00 15 54](https://user-images.githubusercontent.com/20127664/67064034-4129c180-f13f-11e9-94fc-b78408b69a1d.jpeg)

**Comment by Jailsonk8** [comment]
> # Screenshots of Game
> ![WhatsApp Image 2019-10-18 at 00 20 07](https://user-images.githubusercontent.com/20127664/67064032-4129c180-f13f-11e9-8560-818fa4efb64e.jpeg)
> ![WhatsApp Image 2019-10-18 at 00 19 34](https://user-images.githubusercontent.com/20127664/67064033-4129c180-f13f-11e9-9e3f-e2f2b1e7ea67.jpeg)
> ![WhatsApp Image 2019-10-18 at 00 15 54](https://user-images.githubusercontent.com/20127664/67064034-4129c180-f13f-11e9-94fc-b78408b69a1d.jpeg)
